# Generated by Django 3.0.6 on 2020-06-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='pw')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('nick_name', models.CharField(blank=True, max_length=50, verbose_name='nick')),
                ('age', models.IntegerField(blank=True, verbose_name='age')),
                ('score', models.FloatField(blank=True, verbose_name='score')),
                ('gender', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
