# Generated by Django 3.0.6 on 2020-06-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('aff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.Affilate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'review',
                'unique_together': {('user_id', 'aff_name')},
            },
        ),
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('aff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.Affilate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'my_company',
                'unique_together': {('user_id', 'aff_name')},
            },
        ),
    ]
