# Generated by Django 3.0.6 on 2020-06-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True)),
                ('marketC', models.CharField(blank=True, max_length=50)),
                ('intro', models.TextField()),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='Affilate',
            fields=[
                ('affilate', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('c_name', models.ForeignKey(db_column='c_name', on_delete=django.db.models.deletion.CASCADE, to='superuser.Company')),
            ],
            options={
                'db_table': 'hire_info',
                'unique_together': {('affilate', 'c_name')},
            },
        ),
    ]
